Repository TechCafeFreedom/TODONE, pull requests merged in 2020-04, with the labels that each got.

#63 Feat/home
  app/src/main/java/com/techcafe/todone/MainActivity.kt
  buildSrc/src/main/java/dependencies/Dep.kt
  corecomponent/androidcomponent/src/main/java/com/techcafe/todone/androidcomponent/BindingAdapter.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/LabelEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/ProjectWithLabelDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/TodoWithLabelDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/entity/LabelEntity.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/entity/ProjectWithLabel.kt
  data/repository/src/main/java/com/techcafe/todone/repository/TestRepository.kt
  data/repository/src/main/java/com/techcafe/todone/repository/di/modules.kt
  data/repository/src/main/java/com/techcafe/todone/repository/impl/TestRepositoryImpl.kt
  features/auth/src/main/java/com/techcafe/todone/auth/SignInActivity.kt
  features/home/build.gradle
  features/home/src/main/java/com/techcafe/todone/home/HomeController.kt
  features/home/src/main/java/com/techcafe/todone/home/HomeFragment.kt
  features/home/src/main/java/com/techcafe/todone/home/package-info.java
  features/home/src/main/res/drawable/ic_add_black_24dp.xml
  features/home/src/main/res/layout/fragment_home.xml
  features/home/src/main/res/layout/model_empty.xml
  features/home/src/main/res/layout/model_item.xml
  features/home/src/main/res/values/strings.xml
  features/profile/src/main/java/com/techcafe/todone/profile/ProfileFragment.kt
  features/profile/src/main/java/com/techcafe/todone/profile/edit/EditProfileFragment.kt
  features/profile/src/main/java/com/techcafe/todone/profile/edit/ProfileEditorViewModel.kt
  features/settings/src/main/java/com/techcafe/todone/settings/SettingController.kt
Labels: review fixing, review ready

#65 Settings画面とりあえずレイアウトだけ作ったよ
  features/settings/build.gradle
  features/settings/src/main/java/com/techcafe/todone/settings/SettingsFragment.kt
  features/settings/src/main/res/values/arrays.xml
  features/settings/src/main/res/values/strings.xml
  features/settings/src/main/res/xml/preferences.xml
Labels: review ready

#71 Feat/WithTable
  data/db/src/main/java/com/techcafe/todone/db/di/modules.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/LocalDataBase.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/ProjectEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/TodoEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/UserEntityDao.kt
  data/repository/src/main/java/com/techcafe/todone/repository/TestRepository.kt
  data/repository/src/main/java/com/techcafe/todone/repository/di/modules.kt
  data/repository/src/main/java/com/techcafe/todone/repository/impl/TestRepositoryImpl.kt
  features/profile/src/main/java/com/techcafe/todone/profile/edit/ProfileEditorViewModel.kt
Labels: review ready

#69 Resultクラスを定義
  model/src/main/java/techcafe/todone/Result.kt
Labels: improvement DX, review ready

#79 delete now
  .idea/gradle.xml
  app/build.gradle
  corecomponent/androidcomponent/src/main/res/menu/menu_nav_bottom.xml
  corecomponent/androidcomponent/src/main/res/navigation/navigation.xml
  features/now/.gitignore
  features/now/build.gradle
  features/now/consumer-rules.pro
  features/now/proguard-rules.pro
  features/now/src/androidTest/java/com/techcafe/todone/now/ExampleInstrumentedTest.kt
  features/now/src/main/AndroidManifest.xml
  features/now/src/main/java/com/techcafe/todone/now/NowFragment.kt
  features/now/src/main/res/layout/fragment_now.xml
  features/now/src/main/res/values/strings.xml
  features/now/src/test/java/com/techcafe/todone/now/ExampleUnitTest.kt
  settings.gradle
Labels: review ready

#83 projects module削除
  .idea/gradle.xml
  app/build.gradle
  app/src/main/java/com/techcafe/todone/MainActivity.kt
  corecomponent/androidcomponent/src/main/res/menu/menu_nav_drawer.xml
  corecomponent/androidcomponent/src/main/res/navigation/navigation.xml
  features/projects/.gitignore
  features/projects/build.gradle
  features/projects/consumer-rules.pro
  features/projects/proguard-rules.pro
  features/projects/src/androidTest/java/com/techcafe/todone/ExampleInstrumentedTest.kt
  features/projects/src/main/AndroidManifest.xml
  features/projects/src/main/java/com/techcafe/todone/projects/ProjectsFragment.kt
  features/projects/src/main/res/layout/fragment_projects.xml
  features/projects/src/main/res/values/strings.xml
  features/projects/src/test/java/com/techcafe/todone/ExampleUnitTest.kt
  settings.gradle
Labels: review ready

#85 Feat/dokka
  build.gradle
  buildSrc/src/main/java/dependencies/Dep.kt
  gradle/common.gradle
Labels: review ready

#87 Timberの導入
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/com/techcafe/todone/App.kt
  buildSrc/src/main/java/dependencies/Dep.kt
  features/home/src/main/java/com/techcafe/todone/home/HomeFragment.kt
  gradle/common.gradle
Labels: review ready

#90 Hello Github Actions
  .github/workflows/android.yml
  Dangerfile
  Gemfile
  corecomponent/androidcomponent/src/androidTest/java/com/techcafe/todone/androidcomponent/ExampleInstrumentedTest.kt
  corecomponent/androidcomponent/src/test/java/com/techcafe/todone/androidcomponent/ExampleUnitTest.kt
  features/aboutapp/src/androidTest/java/com/techcafe/todone/ExampleInstrumentedTest.kt
  features/aboutapp/src/main/AndroidManifest.xml
  features/aboutapp/src/main/java/com/techcafe/todone/aboutapp/AboutAppFragment.kt
  features/aboutapp/src/test/java/com/techcafe/todone/ExampleUnitTest.kt
  features/home/src/androidTest/java/com/techcafe/todone/home/ExampleInstrumentedTest.kt
  features/home/src/test/java/com/techcafe/todone/home/ExampleUnitTest.kt
  features/notifications/src/androidTest/java/com/techcafe/todone/notifications/ExampleInstrumentedTest.kt
  features/notifications/src/test/java/com/techcafe/todone/notifications/ExampleUnitTest.kt
  features/profile/src/androidTest/java/com/techcafe/todone/profile/ExampleInstrumentedTest.kt
  features/profile/src/test/java/com/techcafe/todone/profile/ExampleUnitTest.kt
Labels: improvement DX, review ready

#88 英語と日本語の多言語に対応
  corecomponent/androidcomponent/src/main/res/values-ja/strings.xml
  corecomponent/androidcomponent/src/main/res/values/arrays.xml
  corecomponent/androidcomponent/src/main/res/values/strings.xml
  features/settings/src/main/java/com/techcafe/todone/settings/SettingsFragment.kt
  features/settings/src/main/res/xml/preferences.xml
Labels: review ready

#82 要件通りのDBを構築
  data/db/src/main/java/com/techcafe/todone/db/di/modules.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/LocalDataBase.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/converter/DateConverter.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/converter/DateTime.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/BoardEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/BoardWithLabelDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/CardEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/CardWithLabelDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/LabelEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/ProjectEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/ProjectWithLabelDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/TodoEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/TodoWithLabelDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/UserEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/UserWithBoardDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/entity/BoardEntity.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/entity/CardEntity.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/entity/KanbanEntity.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/entity/LabelEntity.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/entity/ProjectEntity.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/entity/ProjectWithLabel.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/entity/TodoEntity.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/middleEntity/BoardWithKanban.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/middleEntity/BoardWithLabel.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/middleEntity/CardWithLabel.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/middleEntity/KanbanWithCard.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/middleEntity/ProjectWithTodo.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/middleEntity/UserWithBoard.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/middleEntity/UserWithProject.kt
  data/repository/src/main/java/com/techcafe/todone/repository/TestRepository.kt
  data/repository/src/main/java/com/techcafe/todone/repository/di/modules.kt
  data/repository/src/main/java/com/techcafe/todone/repository/impl/TestRepositoryImpl.kt
Labels: review ready

#103 Daoにdokkaのコメントを導入する
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/BoardEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/BoardWithLabelDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/CardEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/CardWithLabelDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/LabelEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/UserEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/UserWithBoardDao.kt
  data/repository/src/main/java/com/techcafe/todone/repository/impl/TestRepositoryImpl.kt
Labels: review ready

#108 common.gradle に CoroutineとLiveDataの依存関係を追加
  app/build.gradle
  buildSrc/src/main/java/dependencies/Dep.kt
  data/api/build.gradle
  features/board/build.gradle
  features/profile/build.gradle
  features/settings/build.gradle
  gradle/common.gradle
Labels: review ready

#133 よさげなアニメーション付けた
  features/board/src/main/java/com/techcafe/todone/board/BoardFragment.kt
  features/board/src/main/java/com/techcafe/todone/board/animation/ZoomOutPageTransformer.kt
  features/board/src/main/res/layout/view_item.xml
Labels: review ready

#136 ダークテーマ再び
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  corecomponent/androidcomponent/src/main/res/values-ja/strings.xml
  corecomponent/androidcomponent/src/main/res/values/arrays.xml
  corecomponent/androidcomponent/src/main/res/values/strings.xml
  features/settings/src/main/java/com/techcafe/todone/settings/SettingsFragment.kt
  features/settings/src/main/res/xml/preferences.xml
Labels: review ready

#130 FirebaseUIからFirebaseAuthに変更
  app/src/main/java/com/techcafe/todone/MainActivity.kt
  app/src/main/java/com/techcafe/todone/di/modules.kt
  buildSrc/src/main/java/dependencies/Dep.kt
  corecomponent/androidcomponent/src/main/res/menu/menu_nav_drawer.xml
  corecomponent/androidcomponent/src/main/res/navigation/navigation.xml
  corecomponent/androidcomponent/src/main/res/navigation/navigation_auth.xml
  corecomponent/androidcomponent/src/main/res/navigation/navigation_sign_in.xml
  corecomponent/androidcomponent/src/main/res/values-ja/strings.xml
  corecomponent/androidcomponent/src/main/res/values/strings.xml
  data/repository/build.gradle
  data/repository/src/main/java/com/techcafe/todone/repository/AuthRepository.kt
  data/repository/src/main/java/com/techcafe/todone/repository/di/modules.kt
  data/repository/src/main/java/com/techcafe/todone/repository/impl/AuthRepositoryImpl.kt
  features/auth/build.gradle
  features/auth/src/main/AndroidManifest.xml
  features/auth/src/main/java/com/techcafe/todone/auth/AuthActivity.kt
  features/auth/src/main/java/com/techcafe/todone/auth/SignInActivity.kt
  features/auth/src/main/java/com/techcafe/todone/auth/di/modules.kt
  features/auth/src/main/java/com/techcafe/todone/auth/signin/SignInFragment.kt
  features/auth/src/main/java/com/techcafe/todone/auth/signup/SignUpFragment.kt
  features/auth/src/main/java/com/techcafe/todone/auth/signup/SignUpViewModel.kt
  features/auth/src/main/res/layout/activity_auth.xml
  features/auth/src/main/res/layout/fragment_sign_in.xml
  features/auth/src/main/res/layout/fragment_sign_up.xml
  model/src/main/java/techcafe/todone/Result.kt
  model/src/main/java/techcafe/todone/Results.kt
  model/src/main/java/techcafe/todone/User.kt
Labels: review ready

#142 プロフィールからボードに戻ったときにクラッシュするバグ修正
  corecomponent/androidcomponent/src/main/res/navigation/navigation.xml
  features/profile/src/main/java/com/techcafe/todone/profile/ProfileFragment.kt
Labels: review ready

#144 Results型をもっと簡単に書く
  model/src/main/java/techcafe/todone/Results.kt
Labels: review ready

#134 【CreateBoard】画面の作成
  app/src/main/java/com/techcafe/todone/di/modules.kt
  corecomponent/androidcomponent/src/main/res/values-ja/strings.xml
  corecomponent/androidcomponent/src/main/res/values/strings.xml
  features/board/src/main/java/com/techcafe/todone/board/BoardFragment.kt
  features/board/src/main/java/com/techcafe/todone/board/CreateBoardFragment.kt
  features/board/src/main/java/com/techcafe/todone/board/viewModel/BoardCreateViewModel.kt
  features/board/src/main/res/layout/fragment_create.xml
Labels: review ready

#149 DBに合わせてDaoを再構築
  app/src/main/java/com/techcafe/todone/di/modules.kt
  data/db/src/main/java/com/techcafe/todone/db/di/modules.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/LocalDataBase.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/BoardEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/CardEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/CardWithLabelDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/KanbanEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/LabelEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/UserEntityDao.kt
  data/db/src/main/java/com/techcafe/todone/db/internal/dao/UserWithBoardDao.kt
  data/repository/src/main/java/com/techcafe/todone/repository/di/modules.kt
  data/repository/src/main/java/com/techcafe/todone/repository/impl/TestRepositoryImpl.kt
  features/board/src/main/java/com/techcafe/todone/board/viewModel/BoardCreateViewModel.kt
Labels: review ready
